version: "2"

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: standard
  enable:
    - gosec
    - misspell
    - unconvert
    - unparam
    - wastedassign

  exclusions:
    presets:
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
