GO ?= go

# go tools versions
GOLANGCI=github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.9.0
gofumpt=mvdan.cc/gofumpt@v0.9.2
govulncheck=golang.org/x/vuln/cmd/govulncheck@v1.1.4
goimports=golang.org/x/tools/cmd/goimports@v0.42.0
gotestsum=gotest.tools/gotestsum@v1.13.0

.PHONY: fmt
fmt: ## Format code
	go mod tidy
	$(GO) fix ./...
	$(GO) run $(gofumpt) -l -w -extra .
	find . -type f -name '*.go' -exec grep -L -E 'Code generated by .*\. DO NOT EDIT.' {} + | xargs $(GO) run $(goimports) -format-only -w -local=github.com/lvrach

.PHONY: lint
lint: fmt ## Lint code
	$(GO) run $(GOLANGCI) run -v

.PHONY: vulncheck
vulncheck: ## Run vulnerability check
	$(GO) run $(govulncheck) ./...

.PHONY: test
test: ## Run tests
	$(GO) run $(gotestsum) --format pkgname-and-test-fails -- -race -v -failfast -shuffle=on -coverprofile=profile.out -covermode=atomic -coverpkg=./... -vet=all --timeout=5m ./...

.PHONY: build
build: ## Build binary
	$(GO) build -o bin/slack-social .

.PHONY: install
install: ## Install binary
	$(GO) install .

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help
