package manifest

import (
	"fmt"
	"strings"
)

// Generate returns a Slack app manifest YAML for the given app name.
func Generate(appName string) string {
	appName = strings.TrimSpace(appName)
	if appName == "" {
		appName = "slack-social-ai"
	}

	return fmt.Sprintf(`# Generated by slack-social-ai
# Import at https://api.slack.com/apps?new_app=1 → "From a manifest"
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: %s
  description: Post messages to Slack from the terminal
features:
  bot_user:
    display_name: %s
    always_online: false
oauth_config:
  scopes:
    bot:
      - incoming-webhook
settings:
  incoming_webhooks:
    incoming_webhooks_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
`, appName, appName)
}
